### ISSUE TITLE
dio plugin upgrade

### ISSUE THREAD

**Issue by pranali-g** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#24]
Hello,

Please upgrade latest dio plugin, because I have used latest dio version in my flutter project and latest flutter version.

**Comment by Arifur05** [comment]
@Shrutimahajan I have updated the Dio plugin version and opened a pull request.

**Comment by aykutuludag** [comment]
Problem is most probably about CORS. Look at the error: https://github.com/Shrutimahajan/Google-AutoComplete-TextField-Flutter/issues/7#issuecomment-2198373741
