### ISSUE TITLE
The predictions in new version [2.0.2] is not as accurate as the version [1.0.5]

### ISSUE THREAD

**Issue by subinsv** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#3]
Hi,
Thanks for this wonderful plugin.

We recently migrated the google_places_flutter plugin from version 1.0.5 to 2.0.2 and the accuracy of predication has been degraded.

Screenshot from 1.0.5
<img width="202" alt="expected" src="https://user-images.githubusercontent.com/26520063/95623328-b1d59680-0a92-11eb-9b0e-ba583e6f4664.png">

Screenshot from 2.0.2
<img width="200" alt="current" src="https://user-images.githubusercontent.com/26520063/95623356-bef28580-0a92-11eb-812d-d3bf1525d37a.png">

The screenshot from 1.0.5 seems to return proper address when searched.
Is there some search algorithm changed.
Is there a way to get back the previous implementation.

**Comment by Shrutimahajan** [comment]
I will check and update you ASAP.

**Comment by Shrutimahajan** [comment]
@subinsv 
Please comment 
          // countries: ["in", "fr"],
You will get the same result as of the previous implementation.

**Comment by subinsv** [comment]
Thanks @Shrutimahajan 

But we are not calling countries in our code.
This is the code we use. No changes made during update to 2.0.2. Same code works for 1.0.5 without any issues.
```dart
GooglePlaceAutoCompleteTextField(
                textEditingController: _controller,
                googleAPIKey: AppStrings.GOOGLE_PLACE_API_KEY,
                debounceTime: 800,
                itmClick: (Prediction prediction) {
                  _controller.text = prediction.description;
                  _controller.selection = TextSelection.fromPosition(
                    TextPosition(
                      offset: prediction.description.length,
                    ),
                  );
                  //other logic here
                },
              ),
```

**Comment by subinsv** [comment]
I think I found the issue.
In this commit the URL parameters are changed https://github.com/Shrutimahajan/Google-AutoComplete-TextField-Flutter/commit/b13dda6266b7079b0de32b4f68694cddde088603


The URL parameters that is added -> &types=establishment&radius=500
This causes different json response. If this is removed, I get the previous results. Is this change intentional?

**Comment by Shrutimahajan** [comment]
@subinsv 
This change is unintentional. I will check. and release a new version.

**Comment by shruti-techindustan** [comment]
@subinsv 
Thanks for finding the issue. I  will remove the "type" key  as currently, it returns only business results.

**Comment by subinsv** [comment]
Thanks @Shrutimahajan :)

**Comment by shruti-techindustan** [comment]
@subinsv 
Please check the new release. and I am closing it.

**Comment by subinsv** [comment]
Thanks @Shrutimahajan 

The latest version is working as expected.
I will close this issue
