### ISSUE TITLE
DioErrorHandler properties missing

### ISSUE THREAD

**Issue by darul9061** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#39]
../../../.pub-cache/hosted/pub.dev/google_places_flutter-2.0.6/lib/DioErrorHandler.dart:18:25: Error: Member not found: 'connectTimeout'.
      case DioErrorType.connectTimeout:
                        ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/google_places_flutter-2.0.6/lib/DioErrorHandler.dart:21:25: Error: Member not found: 'other'.
      case DioErrorType.other:
                        ^^^^^
../../../.pub-cache/hosted/pub.dev/google_places_flutter-2.0.6/lib/DioErrorHandler.dart:33:25: Error: Member not found: 'response'.
      case DioErrorType.response:
                        ^^^^^^^^
Target kernel_snapshot failed: Exception

This error was found running with dio version 5.4.0

Please help fix it.

**Comment by asmrtfm** [comment]
Solution seems straight forward (https://pub.dev/documentation/dio/latest/dio/DioErrorType.html)

I was going to try to submit a pull request but I'm not seeing the affected file (lib/DioErrorHandler.dart) in repo...

**Comment by darul9061** [comment]
will appreciate the pull request

**Comment by dumpster-of-things** [comment]
I am new to the flutter ecosystem, so it's possible that I am confused, but when I pull down this project as a dependency, it contains files under the lib directory which are not shown here on github despite being the same version/branch.  I resolved the errors by editing one these missing files ("lib/DioErrorHandler.dart") replacing its usage of outdated Dio syntax as per their changelog linked above in my post.

**Comment by asmrtfm** [comment]
I am new to the flutter ecosystem, so it's possible that I am confused, but when I pull down this project as a dependency, it contains files under the lib directory which are not shown here on github despite being the same version/branch. I resolved the errors by editing one these missing files ("lib/DioErrorHandler.dart") replacing its usage of outdated Dio syntax as per their changelog linked above in my post.

**Comment by Shrutimahajan** [comment]
Please check the new version.
