### ISSUE TITLE
Padding should be optional

### ISSUE THREAD

**Issue by darshanvachhani08** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#40]
This Padding should be optional. Users can pass whatever they want.
<img width="712" alt="Screenshot 2024-01-02 at 12 41 13 PM" src="https://github.com/Shrutimahajan/Google-AutoComplete-TextField-Flutter/assets/50709093/5bdd398a-a1ff-4f49-8ed8-6b70e17363f8">

**Comment by Shrutimahajan** [comment]
@darshanvachhani08 
Please check the new version for this. Added **containerHorizontalPadding**,**containerVerticalPadding** for this.
