### ISSUE TITLE
[CORS] Cors-anywhere is now in limited acces 

### ISSUE THREAD

**Issue by BaptisteBAYLE** [Shrutimahajan/Google-AutoComplete-TextField-Flutter#58]
When we use the plugin on a web environment, the proxy cors-anywhere.herokuapp.com/ is added in front of the Google Maps API link. This request returns an unauthorized error while cors-anywhere restricted their proxy.  

I suggest that the proxyURL can be passed as an input or an ENV_VARIABLE. 

I use 
google_places_flutter: ^2.0.8
environment:
  sdk: ">=2.12.0 <3.0.0"

**Comment by aykutuludag** [comment]
I wrote exactly same suggestion about 2-3 months ago but they don't care I suppose. This plugin either doesn't updated or they don't care Flutter Web.

https://github.com/Shrutimahajan/Google-AutoComplete-TextField-Flutter/issues/7#issuecomment-2198373741
